### ISSUE TITLE
getting ewd-document-store error when trying this repo with docker container

### ISSUE THREAD

**Issue by tony-shannon** [robtweed/qewd-server-rest-examples#4]
Hi Rob
Been trying to reuse this repo with the latest docker container, not sure it still should be working?

see here
myVPS_IP:8080/test/me
{
  "error": "No Document Store has been created - you must use ewd-document-store!"
}

![image](https://user-images.githubusercontent.com/939996/50738628-fd785380-11cd-11e9-8a00-377ef38bd804.png)

have tried this on 2 machines now, same error

![image](https://user-images.githubusercontent.com/939996/50738634-1e40a900-11ce-11e9-82ed-0a4e1e94240a.png)

**Comment by robtweed** [comment]
OK there's a bug that's crept in as a result of the QEWD-Up work.  I'll fix it in the next day or two, but in the meantime edit your startup_config.json file and specify the database type as 'gtm':

{
  "managementPassword": "keepThisSecret!",
  "serverName": "QEWD Server",
  "port": 8080,
  "poolSize": 2,
  "database": {
    "type": "gtm"
  }
}

Then restart the Docker container

I think it should be fine then

Rob

**Comment by tony-shannon** [comment]
That did the trick, many thanks Rob.
used docker stop and then docker start to restart

![image](https://user-images.githubusercontent.com/939996/50739858-ae3a1f00-11dd-11e9-9c90-e49730eda902.png)


Related Q: should database as "redis" work if wanting to use some of this qewd docker related material? 
https://www.slideshare.net/robtweed/ewd-3-training-course-part-42-the-qewd-docker-appliance

**Comment by robtweed** [comment]
Latest version of rtweed/qewd-server (and RPi version rtweed/qewd-server-rpi) now defaults to a database type of 'gtm' (which is synonymous with YottaDB for the purposes of QEWD) if the startup file doesn't define the database type.  To get the latest version: docker pull rtweed/qewd-server
